[package]
name = "quartz-engine"
version = "0.1.0"
authors = ["= <hjalte.nannestad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quartz-render = { path = "../quartz-render" }
egui = "0.12"
libloading = "0.7"